@echo off
setlocal EnableExtensions EnableDelayedExpansion

set "SCRIPT_DIR=%~dp0"
if "%SCRIPT_DIR:~-1%"=="\" set "SCRIPT_DIR=%SCRIPT_DIR:~0,-1%"
set "QUIET=0"

if /I "%~1"=="--quiet" set "QUIET=1"

call :find_project_root "%SCRIPT_DIR%"
if errorlevel 1 exit /b 1

call :find_sdk_root
if errorlevel 1 exit /b 1

set "OHOS_NATIVE=%SDK_ROOT%\default\openharmony\native"
set "HVIGOR_JS=%STUDIO_ROOT%\tools\hvigor\hvigor\bin\hvigor.js"
set "LOCAL_PROPERTIES=%PROJECT_DIR%\local.properties"

if not exist "%OHOS_NATIVE%\build-tools\cmake\bin\cmake.exe" (
  echo [ERROR] Invalid OHOS native SDK path: %OHOS_NATIVE%
  exit /b 1
)

call :require_cmd node "Node.js"
if errorlevel 1 exit /b 1

call :require_cmd cargo "Rust cargo"
if errorlevel 1 exit /b 1

call :require_cmd rustup "rustup"
if errorlevel 1 exit /b 1

set "PATH=%OHOS_NATIVE%\build-tools\cmake\bin;%OHOS_NATIVE%\llvm\bin;%PATH%"
set "DEVECO_SDK_HOME=%SDK_ROOT%"
set "OHOS_SDK_NATIVE=%OHOS_NATIVE%"
set "OHOS_NDK_HOME=%OHOS_NATIVE%"
set "SDK_NATIVE=%OHOS_NATIVE%"

setx DEVECO_SDK_HOME "%SDK_ROOT%" >nul
setx OHOS_NATIVE "%OHOS_NATIVE%" >nul
setx OHOS_SDK_NATIVE "%OHOS_NATIVE%" >nul
setx OHOS_NDK_HOME "%OHOS_NATIVE%" >nul

> "%LOCAL_PROPERTIES%" echo # Auto-generated by setup_env.bat
>> "%LOCAL_PROPERTIES%" echo sdk.dir=%SDK_ROOT:\=/%
>> "%LOCAL_PROPERTIES%" echo ohos.native.dir=%OHOS_NATIVE:\=/%

call :ensure_rust_target aarch64-unknown-linux-ohos
if errorlevel 1 exit /b 1

call :ensure_rust_target x86_64-unknown-linux-ohos
if errorlevel 1 exit /b 1

if exist "%HVIGOR_JS%" (
  node "%HVIGOR_JS%" --stop-daemon >nul 2>&1
)

if "%QUIET%"=="0" (
  echo [OK] DevEco Studio root: %STUDIO_ROOT%
  echo [OK] DevEco SDK root: %SDK_ROOT%
  echo [OK] OHOS native SDK: %OHOS_NATIVE%
  echo [OK] local.properties updated: %LOCAL_PROPERTIES%
  echo [OK] User environment variables updated:
  echo      DEVECO_SDK_HOME
  echo      OHOS_NATIVE
  echo      OHOS_SDK_NATIVE
  echo      OHOS_NDK_HOME
  echo [OK] rustup OHOS targets are installed.
)

endlocal & (
  set "DEVECO_SDK_HOME=%SDK_ROOT%"
  set "OHOS_NATIVE=%OHOS_NATIVE%"
  set "OHOS_SDK_NATIVE=%OHOS_NATIVE%"
  set "OHOS_NDK_HOME=%OHOS_NATIVE%"
  set "SDK_NATIVE=%OHOS_NATIVE%"
) & exit /b 0

:find_project_root
set "SEARCH_DIR=%~f1"
if not defined SEARCH_DIR set "SEARCH_DIR=%CD%"

:find_project_root_loop
if exist "%SEARCH_DIR%\oh-package.json5" if exist "%SEARCH_DIR%\entry\build-profile.json5" (
  set "PROJECT_DIR=%SEARCH_DIR%"
  exit /b 0
)

for %%I in ("%SEARCH_DIR%\..") do set "PARENT_DIR=%%~fI"
if /I "%PARENT_DIR%"=="%SEARCH_DIR%" (
  echo [ERROR] Failed to locate Agent project root from:
  echo         %~f1
  echo         Expected a directory containing oh-package.json5 and entry\build-profile.json5
  exit /b 1
)

set "SEARCH_DIR=%PARENT_DIR%"
goto :find_project_root_loop

:find_sdk_root
set "SDK_ROOT="
set "STUDIO_ROOT="

if defined DEVECO_SDK_HOME if exist "%DEVECO_SDK_HOME%\default\openharmony\native" (
  set "SDK_ROOT=%DEVECO_SDK_HOME%"
)

if not defined SDK_ROOT (
  for %%D in (
    "C:\Program Files\Huawei\DevEco Studio\sdk"
    "D:\develop\deveco\DevEco Studio\sdk"
  ) do (
    if not defined SDK_ROOT if exist "%%~D\default\openharmony\native" set "SDK_ROOT=%%~D"
  )
)

if not defined SDK_ROOT (
  echo [ERROR] DevEco SDK not found.
  echo         Expected a valid SDK under a path like:
  echo         C:\Program Files\Huawei\DevEco Studio\sdk
  exit /b 1
)

for %%I in ("%SDK_ROOT%\..") do set "STUDIO_ROOT=%%~fI"

if not exist "%STUDIO_ROOT%\tools\hvigor\hvigor\bin\hvigor.js" (
  echo [ERROR] Hvigor entrypoint not found under DevEco Studio:
  echo         %STUDIO_ROOT%
  exit /b 1
)

exit /b 0

:require_cmd
where %~1 >nul 2>&1
if errorlevel 1 (
  echo [ERROR] %~2 not found in PATH.
  exit /b 1
)
exit /b 0

:ensure_rust_target
rustup target list --installed | findstr /I /X "%~1" >nul
if errorlevel 1 (
  if "%QUIET%"=="0" echo [INFO] Installing Rust target %~1 ...
  rustup target add %~1
  if errorlevel 1 (
    echo [ERROR] Failed to install Rust target %~1.
    exit /b 1
  )
)
exit /b 0
